var projectsData = [
  {
    category: 'Category: 201 Project',
    name:       'Pizza 3000',
    summary:    '<p>A webpage for a Pizza restaurant that builds tables via JS and dynamically updates sales numbers for various locations</p> <p>Pommy ipsum wibbly-wobbly timey-wimey stuff argy-bargy rubbish, muck about Amelia Pond bog off biscuits hard cheese old boy, Big Ben utter shambles I could reet fancy a. Knee high to a grasshopper ill be a monkeys uncle sausage roll got his end away rivetting stuff alright geezer sweets damn up North, and scatterbrained knows bugger all about nowt have a butchers at this Southeners tosser. Eton mess get away with ya jellied eels guinness, gosh. Fancy a cuppa is she avin a laugh well fit shepherds pie apple and pears flip flops cockney willy, one off knackered by eck love splendid copper ont goggle box.</p>',
    creator:      'Yvonne Hayes',
    collaborators:   'none',
    finishedOn: '2016-03-20',
    locationUrl: '<a href="https://github.com/YvonneHayes/201Week2_Pizza" target="_blank">Click here to view on GitHub</a>',
  },
  {
    category: 'Category: 201 Project',
    name:       'BusMall',
    summary:    '<p>A webpag with a professional looking landing page and a cartoon/fun themed voting page, that counts clicks on a certain image and displays results in charts made with canvas and charts.js</p> <p>Pommy ipsum spend a penny sweet fanny adams terribly shortbread, damn Moriarty accordingly completely crackers. Clotted cream a right toff fancied a flutter a tenner doing my head in, tallywhacker flabbergasted on a stag do. Nuthouse rather up North a right royal knees up houlligan plum pudding pompous, the chippy what a doddle dont get your knickers in a twist old girl lost the plot cotton on, penny-dreadful argy-bargy a week on Sunday could be a bit of a git curry sauce. Bovver boots its me peepers bog roll marvelous jolly bobby, tallywhacker Sherlock ey up chuck plum pudding, curry sauce fork out for sooth indeed. </p>',
    creator:      'Yvonne Hayes',
    collaborators:   'none',
    finishedOn: '2016-03-28',
    locationUrl:'<a href="https://github.com/YvonneHayes/201Week3_BusMall" target="_blank">Click here to view on GitHub</a>',
  },
  {
    category: 'Category: Final Project',
    name:       'Trash Brigade',
    summary:    '<p>A webpag for a local charity in Mexico. It has an image gallery that fades in and two forms that utilize local storage and verify the user input. </p> <p>Pommy ipsum punter pennyboy oo ecky thump a cracking odds and sods the dogs dinner, black cab a right toff eton mess flog a dead horse nuthouse. Bit of alright what a load of cobblers its me peepers ask your mother if Dalek lost the plot, what a doddle there with one would be honoured to any road, best be off a bottle of plonk tally-ho, spend a penny manky on a stag do in the jacksy. Oo ecky thump one would be honoured to chuffed knows bugger all about nowt grab a jumper Dalek rumpy pumpy middle class, numbskull golly you mean it aint me noggin ey up duck odds and sods. At the boozer Bad Wolf narky had a barney with the inlaws hadnt done it in donkeys years, porky-pies scouser by eck love. </p>',
    creator:      'Yvonne Hayes',
    collaborators:   'Randy Gylling and Johnny Luangphasy',
    finishedOn: '2016-04-07',
    locationUrl: '<a href="https://github.com/YvonneHayes/TrashBrigade" target="_blank">Click here to view on GitHub</a>',
  },
  {
    category: 'Category: Final Project',
    name:       'Super Awesome Project',
    summary: '<p>Pommy ipsum punter pennyboy oo ecky thump a cracking odds and sods the dogs dinner, black cab a right toff eton mess flog a dead horse nuthouse.</p> <p> Bit of alright what a load of cobblers its me peepers ask your mother if Dalek lost the plot, what a doddle therewith one would be honoured to any road, best be off a bottle of plonk tally-ho, spend a penny manky on a stag do in the jacksy. Oo ecky thump one would be honoured to chuffed knows bugger all about nowt grab a jumper Dalek rumpy pumpy middle class, numbskull golly you mean it aint me noggin ey up duck odds and sods. At the boozer Bad Wolf narky had a barney with the inlaws hadnt done it in donkeys years, porky-pies scouser by eck love. </p>',
    creator:      'Yvonne Hayes',
    collaborators:   'Some super dope peeps',
    finishedOn: '2016-04-02',
    locationUrl: '<a href="https://github.com/YvonneHayes/SuperAwesome" target="_blank">Click here to view on GitHub</a>',
  },
];
